services:

  mongo:
    image: mongo:7
    container_name: food-delivery-mongo
    restart: unless-stopped

    volumes:
      - mongo-data:/data/db

    networks:
      - food-delivery-network


  backend:
    image: food-delivery-app:${IMAGE_TAG:-latest}
    container_name: food-delivery-backend
    restart: unless-stopped

    depends_on:
      - mongo

    environment:
      NODE_ENV: production
      PORT: 5000
      DB_LOCAL_URI: mongodb://mongo:27017/orderit

    ports:
      - "5000:5000"

    networks:
      - food-delivery-network


  frontend:
    image: food-delivery-frontend:${IMAGE_TAG:-latest}
    container_name: food-delivery-frontend
    restart: unless-stopped

    ports:
      - "3000:80"

    networks:
      - food-delivery-network


volumes:
  mongo-data:


networks:
  food-delivery-network:
    driver: bridge
